/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 car1.gltf --transform
Author: AFCM (https://sketchfab.com/afcm.contact)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-car-break-low-poly-rigged-539d6b774d3e4b88ba273a68745ce80f
Title: Simple Car Break Low Poly - Rigged
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/car1-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Car_Rig_63">
          <group name="DEF-Body_4" position={[0, 0.315, 0.186]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="SimpleBreakCar_Body_3" position={[0, 0.186, -0.315]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.FrontLights} />
              <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Back_Light} />
              <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.retro} />
              <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Handle} />
              <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.WindScreen} />
              <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Body} />
              <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material} />
              <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Door} />
              <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_9} />
              <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Metal} />
            </group>
          </group>
          <group name="DEF-WheelFtL_6" position={[0.705, 0.347, 1.419]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="SimpleBreakCar_Body_Tire_FL_5" position={[-0.705, 1.419, -0.347]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.TireCenter} />
              <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Tire} />
            </group>
          </group>
          <group name="DEF-WheelFtR_8" position={[-0.702, 0.347, 1.419]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="SimpleBreakCar_Body_Tire_FR_7" position={[0.702, 1.419, -0.347]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.TireCenter} />
              <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Tire} />
            </group>
          </group>
          <group name="DEF-WheelBkL_10" position={[0.705, 0.347, -1.288]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="SimpleBreakCar_Body_Tire_BL_9" position={[-0.705, -1.288, -0.347]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.TireCenter} />
              <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Tire} />
            </group>
          </group>
          <group name="DEF-WheelBkR_12" position={[-0.702, 0.347, -1.288]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="SimpleBreakCar_Body_Tire_BR_11" position={[0.702, -1.288, -0.347]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.TireCenter} />
              <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Tire} />
            </group>
          </group>
          <group name="MCH-WheelrotationFtL_57" position={[0.705, 0.347, 1.419]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="MCH-WheelrotationFtR_58" position={[-0.702, 0.347, 1.419]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="MCH-WheelrotationBkL_59" position={[0.705, 0.347, -1.288]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="MCH-WheelrotationBkR_60" position={[-0.702, 0.347, -1.288]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="MCH-Steeringrotation_62" position={[0, 0.347, 1.419]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="GroundSensorAxleBk_50" position={[0, 0.347, -1.288]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="MCH-RootAxleBk_49" position={[0, 0, -0.347]} />
        </group>
        <group name="GroundSensorAxleFt_55" position={[0, 0.347, 1.419]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="MCH-Steering_54" />
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Ground} scale={20.92} />
      </group>
    </group>
  )
}

useGLTF.preload('/car1-transformed.glb')
