/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 card.gltf --transform
Author: Waldhör Solutions (https://sketchfab.com/mewaldhoer723)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-sd-card-34ec13887eae4ae5961a705a415ea715
Title: Simple SD Card
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/card-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Black-material'].geometry} material={materials.Black} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Yellow-material'].geometry} material={materials.Yellow} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/card-transformed.glb')
