/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 computer.gltf --transform
Author: AlienDev (https://sketchfab.com/AlienDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-computer-pc-cdf9008ddbe842519ecf3b0e2a192282
Title: Low poly Computer / PC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube015_Computer_0.geometry} material={materials.Computer} position={[0, 33.757, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[127.386, 100, 34.639]} />
    </group>
  )
}

useGLTF.preload('/computer-transformed.glb')
