/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 gun1.gltf --transform
Author: Ameer Studio (https://sketchfab.com/uchiha.321abc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flare-gun-6b92ab60292e4c69b59dca3f7102ce94
Title: Flare Gun
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gun1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane004_DefaultMaterial_0.geometry} material={materials.DefaultMaterial} position={[38.194, 185.141, -291.493]} rotation={[-Math.PI / 2, 0, 0]} scale={26.269} />
    </group>
  )
}

useGLTF.preload('/gun1-transformed.glb')
