/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mac.gltf --transform
Author: tzeshi (https://sketchfab.com/timvizesi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-macintosh-608e0f6ce5e9487eb859f48248e1fac4
Title: Apple Macintosh
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['02___Default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Background} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.dark_beige} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.dark_grey} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.darker_beige} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.darker_beige} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.darkest_beige} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.darkest_beige} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.light_beige} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.lighter_beige} />
      </group>
    </group>
  )
}

useGLTF.preload('/mac-transformed.glb')
